import MissionStatus from "./MissionStatus";
import AdaptiveRiskCard from "./AdaptiveRiskCard";
import ConfidenceCard from "./ConfidenceCard";

type MissionBriefProps = {
  summary: string;
  confidence: number;
  riskIndex: number;
  riskLevel: string;
  missionStatus: string;
  recommendation: string;
  actions: string[];
  stakeholders: string[];
};

export default function MissionBrief({
  summary,
  confidence,
  riskIndex,
  recommendation,
}: MissionBriefProps) {
  return (
    <div className="rounded-xl border bg-white p-5 shadow-sm">

      {/* Header */}

      <h2 className="text-2xl font-bold text-slate-900">
        Mission Brief
      </h2>

      <p className="mt-1 text-sm text-slate-500">
        Generated by ARIE
      </p>

      {/* Status Cards */}

      <div className="mt-5 grid grid-cols-3 gap-3">

        <MissionStatus recommendation={recommendation} />

        <AdaptiveRiskCard score={riskIndex} />

        <ConfidenceCard confidence={confidence} />

      </div>

      {/* Recommendation */}

      <div className="mt-5 rounded-lg bg-orange-50 p-4">

        <p className="text-xs font-semibold uppercase tracking-wide text-orange-700">
          Recommendation
        </p>

        <h3 className="mt-2 text-lg font-semibold text-slate-900">
          {recommendation}
        </h3>

      </div>

      {/* Situation Summary */}

      <div className="mt-5">

        <h3 className="text-base font-semibold text-slate-900">
          Situation Summary
        </h3>

        <p className="mt-2 text-sm leading-6 text-slate-600">
          {summary}
        </p>

      </div>

    </div>
  );
}