import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { OperationalReport } from "./types";

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const FOOTER_Y = 30;
const LINE_HEIGHT = 16;

export async function exportReportAsPdf(
  report: OperationalReport,
): Promise<void> {
  const pdf = await PDFDocument.create();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  const newPage = () => {
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;
  };

  const ensureSpace = (required: number) => {
    if (y - required < 70) {
      newPage();
    }
  };

  const drawTextBlock = (
    text: string,
    size = 11,
    isBold = false,
  ) => {
    const activeFont = isBold ? bold : font;

    const lines = text.split("\n");

    for (const line of lines) {
      ensureSpace(LINE_HEIGHT);

      page.drawText(line, {
        x: MARGIN,
        y,
        size,
        font: activeFont,
        color: rgb(0, 0, 0),
      });

      y -= LINE_HEIGHT;
    }
  };

  drawTextBlock("Adaptive Action Intelligence (AAI)", 20, true);
  y -= 6;

  drawTextBlock(report.title, 16, true);
  y -= 10;

  drawTextBlock(`Mission ID: ${report.metadata.missionId}`);
  drawTextBlock(`Audience: ${report.audience}`);
  drawTextBlock(`Generated: ${report.metadata.generatedAt}`);

  y -= 10;

  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 1,
    color: rgb(.8, .8, .8),
  });

  y -= 20;

  for (const section of report.sections) {
    drawTextBlock(section.title, 14, true);
    y -= 4;
    drawTextBlock(section.content);
    y -= 12;
  }

  page.drawLine({
    start: { x: MARGIN, y: FOOTER_Y + 15 },
    end: { x: PAGE_WIDTH - MARGIN, y: FOOTER_Y + 15 },
    thickness: 1,
    color: rgb(.85, .85, .85),
  });

  page.drawText(
    `Generated by ${report.metadata.generatedBy}`,
    {
      x: MARGIN,
      y: FOOTER_Y,
      size: 9,
      font,
      color: rgb(.45, .45, .45),
    }
  );

  page.drawText(report.metadata.version, {
    x: PAGE_WIDTH - 130,
    y: FOOTER_Y,
    size: 9,
    font,
    color: rgb(.45, .45, .45),
  });

  const pdfBytes = await pdf.save();

// Convert Uint8Array to a standard ArrayBuffer
const arrayBuffer = pdfBytes.buffer.slice(
  pdfBytes.byteOffset,
  pdfBytes.byteOffset + pdfBytes.byteLength
) as ArrayBuffer;

const blob = new Blob([arrayBuffer], {
  type: "application/pdf",
});

  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");

  a.href = url;
  a.download = `${report.metadata.missionId}-${report.type}.pdf`;

  a.click();

  URL.revokeObjectURL(url);
}